const BOOKS = [
    {
        "id": "1",
        "title": "JavaScript and JQuery: Interactive Front-End Web Development",
        "author": "David McFarland",
        "year": "2008",
        "language": "English",
        "pages": "1036",
        "price": 1882,
        "description": "This full-color book adopts a visual approach to teaching JavaScript & jQuery, showing you how to make web pages more interactive and interfaces more intuitive through the use of inspiring code examples, infographics, and photography. The content assumes no previous programming experience, other than knowing how to create a basic web page in HTML & CSS. You'll learn how to achieve techniques seen on many popular websites (such as adding animation, tabbed panels, content sliders, form validation, interactive galleries, and sorting data)...",
        "cover": "https://images-na.ssl-images-amazon.com/images/I/51qPrqD4H6L._SX381_BO1,204,203,200_.jpg",
        "quantity": 0
    },
    {
        "id": "2",
        "title": "HTML & CSS: Design and Build Web Sites",
        "author": "Jon Duckett",
        "year": "2011",
        "language": "English",
        "pages": "514",
        "price": 2217,
        "description": "A book about code that doesn't read like a 1980s VCR manual...It's not just for programmers, it's written and presented to make it easy for designers, bloggers, content and e-commerce managers, marketers to learn about the code used to write web pages...",
        "cover": "https://images-eu.ssl-images-amazon.com/images/I/41Z6LTD8QmL.jpg",
        "quantity": 0
    }, 
    {
        "id": "3",
        "title": "Eloquent JavaScript: A Modern Introduction to Programming",
        "author": "Marijn Haverbeke",
        "year": "2011",
        "language": "English",
        "pages": "227",
        "price": 1588,
        "description": "JavaScript lies at the heart of almost every modern web application, from social apps like Twitter to browser-based game frameworks like Phaser and Babylon. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications. This much anticipated and thoroughly revised third edition of Eloquent JavaScript dives deep into the JavaScript language to show you how to write beautiful, effective code. It has been updated to reflect the current state of Java¬Script and web browsers and includes brand-new material on features like class notation, arrow functions, iterators, async functions, template strings, and block scope. A host of new exercises have also been added to test your skills and keep you on track.",
        "cover": "https://images-na.ssl-images-amazon.com/images/I/91q8Jx+j6iL.jpg",
        "quantity": 0
    }, 
    {
        "id": "4",
        "title": "Learning PHP, MySQL, JavaScript, CSS & HTML5: A Step-by-Step Guide to Creating Dynamic Websites",
        "author": "Robin Nixon",
        "year": "2009",
        "language": "English",
        "pages": "1202",
        "price": 3538,
        "description": "Build interactive, data-driven websites with the potent combination of open-source technologies and web standards, even if you only have basic HTML knowledge. With this popular hands-on guide, you’ll tackle dynamic web programming with the help of today’s core technologies: PHP, MySQL, JavaScript, CSS, and HTML5. Explore each technology separately, learn how to use them together, and pick up valuable web programming practices along the way. At the end of the book, you’ll put everything together to build a fully functional social networking site.",
        "cover": "https://images-na.ssl-images-amazon.com/images/I/716iRlYVOML.jpg",
        "quantity": 0        
    }, 
    {
        "id": "5",
        "title": "Don't Make Me Think",
        "author": "Steve Krug",
        "year": "2000",
        "language": "English",
        "pages": "256",
        "price": 3022,
        "description": "Five years and more than 100,000 copies after it was first published, it's hard to imagine anyone working in Web design who hasn't read Steve Krug's 'instant classic' on Web usability, but people are still discovering it every day.  In this second edition, Steve adds three new chapters in the same style as the original: wry and entertaining, yet loaded with insights and practical advice for novice and veteran alike.  Don't be surprised if it completely changes the way you think about Web design.",
        "cover": "https://images-na.ssl-images-amazon.com/images/I/51Swm3TW72L._SX381_BO1,204,203,200_.jpg",
        "quantity": 0
    }, 
    {
        "id": "6",
        "title": "You Don't Know JS: Scope & Closures",
        "author": "Kyle Simpson",
        "year": "2016",
        "language": "English",
        "pages": "105",
        "price": 2579,
        "description": "No matter how much experience you have with JavaScript, odds are you don’t fully understand the language. This concise yet in-depth guide takes you inside scope and closures, two core concepts you need to know to become a more efficient and effective JavaScript programmer. You’ll learn how and why they work, and how an understanding of closures can be a powerful part of your development skillset. Like other books in the 'You Don’t Know JS' series, Scope and Closures dives into trickier parts of the language that many JavaScript programmers simply avoid. Armed with this knowledge, you can achieve true JavaScript mastery.",
        "cover": "https://images-na.ssl-images-amazon.com/images/I/71DjgMQb3bL.jpg",
        "quantity": 0
    }, 
    {
        "id": "7",
        "title": "Designing with Web Standards",
        "author": "Jeffrey Zeldman",
        "year": "2003",
        "language": "English",
        "pages": "533",
        "price": 35096,
        "description": "Designing with Web Standards, first published in 2003 with revised editions in 2007 and 2009, is a web development book by Jeffrey Zeldman. The book’s audience is primarily web development professionals who aim to produce design work that complies with web standards. The work is used as a textbook in over 85 colleges.",
        "cover": "https://images-na.ssl-images-amazon.com/images/I/4196T42AKQL._SX388_BO1,204,203,200_.jpg",
        "quantity": 0
    }, 
    {
        "id": "8",
        "title": "Ruby on Rails Tutorial: Learn Web Development with Rails",
        "author": "Michael Hartl",
        "year": "2010",
        "language": "English",
        "pages": "738",
        "price": 6879,
        "description": "Best-selling author and leading Rails developer Michael Hartl teaches Rails by guiding you through the development of three example applications of increasing sophistication, focusing on the fundamental techniques in web development needed for virtually any kind of application. The updates to this edition include simplified installation via a standard development environment in the cloud, use of the default Rails stack throughout, a light-weight testing approach, an all-new section on image upload, and an all-new chapter on account activation and password resets, including sending email with Rails. This indispensable guide provides integrated tutorials not only for Rails, but also for the essential Ruby, HTML, CSS, and SQL skills you’ll need when developing web applications. Hartl explains how each new technique solves a real-world problem, and then he demonstrates it with bite-sized code that’s simple enough to understand, yet novel enough to be useful. Whatever your previous web development experience, this book will guide you to true Rails mastery.",
        "cover": "https://images-eu.ssl-images-amazon.com/images/I/51330yeWaML._SY445_QL70_ML2_.jpg",
        "quantity": 0
    }, 
    {
        "id": "9",
        "title": "CSS Secrets: Better Solutions to Everyday Web Design Problems",
        "author": "Lea Verou",
        "year": "2014",
        "language": "English",
        "pages": "655",
        "price": 2424,
        "description": "In this practical guide, CSS expert Lea Verou provides 47 undocumented techniques and tips to help intermediate-to advanced CSS developers devise elegant solutions to a wide range of everyday web design problems. Rather than focus on design, CSS Secrets shows you how to solve problems with code. You'll learn how to apply Lea's analytical approach to practically every CSS problem you face to attain DRY, maintainable, flexible, lightweight, and standards-compliant results.",
        "cover": "https://griffio.github.io/public/css_secrets_01.jpg",
        "quantity": 0
    },
    {
        "id": "10",
        "title": "Responsive Web Design with HTML5 and CSS: Develop Future-proof Responsive Websites Using the Latest HTML5 and CSS Techniques",
        "author": "Ben Frain",
        "year": "2020",
        "language": "English",
        "pages": "409",
        "price": 2547,
        "description": "Responsive Web Design with HTML5 and CSS, Third Edition is a renewed and extended version of one of the most comprehensive and bestselling books on the latest HTML5 and CSS tools and techniques for responsive web design. Written in the author's signature friendly and informal style, this edition covers all the newest developments and improvements in responsive web design including better user accessibility, variable fonts and font loading, CSS Scroll Snap, and much, much more. With a new chapter dedicated to CSS Grid, you will understand how it differs from the Flexbox layout mechanism and when you should use one over the other. Furthermore, you will acquire practical knowledge of SVG, writing accessible HTML markup, creating stunning aesthetics and effects with CSS, applying transitions, transformations, and animations, integrating media queries, and more. The book concludes by exploring some exclusive tips and approaches for front-end development from the author.",
        "cover": "https://images-na.ssl-images-amazon.com/images/I/71xVO2SmgaL.jpg",
        "quantity": 0
    },
    {
        "id": "11",
        "title": "The Clean Coder: A Code of Conduct for Professional Programmers",
        "author": "Robert Cecil Martin",
        "year": "2014",
        "language": "English",
        "pages": "244",
        "price": 3099,
        "description": "In The Clean Coder: A Code of Conduct for Professional Programmers, legendary software expert Robert C. Martin introduces the disciplines, techniques, tools, and practices of true software craftsmanship. This book is packed with practical advice–about everything from estimating and coding to refactoring and testing. It covers much more than technique: It is about attitude. Martin shows how to approach software development with honor, self-respect, and pride; work well and work clean; communicate and estimate faithfully; face difficult decisions with clarity and honesty; and understand that deep knowledge comes with a responsibility to act.",
        "cover": "https://jfiaffe.files.wordpress.com/2014/08/the-clean-coder-cover.jpg",
        "quantity": 0
    }, 
    {
        "id": "12",
        "title": "Head First HTML with CSS & XHTML",
        "author": "Elisabeth Freeman and Eric Freeman",
        "year": "2004",
        "language": "English",
        "pages": "704",
        "price": 5493,
        "description": "Learn the real secrets of creating Web pages, and why everything your boss told you about HTML tables is probably wrong (and what to do instead). Most importantly, hold your own with your co-worker (and impress cocktail party guests) when he casually mentions how his HTML is now strict, and his CSS is in an external style sheet. With Head First HTML with CSS & XHTML, you'll avoid the embarrassment of thinking web-safe colors still matter, and the foolishness of slipping a font tag into your pages. Best of all, you'll learn HTML and CSS in a way that won't put you to sleep. If you've read a Head First book, you know what to expect: a visually-rich format designed for the way your brain works. Using the latest research in neurobiology, cognitive science, and learning theory, this book will load HTML, CSS, and XHTML into your brain in a way that sticks.",
        "cover": "https://prashantsani.com/spider/content/images/wp-content/uploads/2012/03/head-first-xhtml-css-cover.jpg",
        "quantity": 0
    },
    {
        "id": "13",
        "title": "ASP.NET Core 3 and React: Hands-On Full Stack Web Development Using ASP.NET Core, React, and TypeScript 3",
        "author": "Carl Rippon",
        "year": "2019",
        "language": "English",
        "pages": "585",
        "price": 2127,
        "description": "This book will start by taking you through React and TypeScript components to build an intuitive single-page application. You’ll understand how to design scalable REST APIs that can integrate with a React-based frontend. You’ll get to grips with the latest features, popular patterns, and tools available in the React ecosystem, including function-based components, React Router, and Redux. The book shows how you can use TypeScript along with React to make the frontend robust and maintainable. You’ll then cover important .NET Core features such as API controllers, attribute routing, and model binding to help you build a sturdy backend. Additionally, you’ll explore API security with ASP.NET Core identity and authorization policies, and write reliable unit tests using both .NET Core and React before you deploy your app to the Azure cloud.",
        "cover": "https://static.packt-cdn.com/products/9781789537611/cover/9781789537611-original.png",
        "quantity": 0
    },
    {
        "id": "14",
        "title": "Web Development with Node and Express: Leveraging the JavaScript Stack",
        "author": "Ethan Brown",
        "year": "2014",
        "language": "English",
        "pages": "360",
        "price": 1200,
        "description": "Learn how to build dynamic web applications with Express, a key component of the Node/JavaScript development stack. In this hands-on guide, author Ethan Brown teaches you the fundamentals through the development of a fictional application that exposes a public website and a RESTful API. You’ll also learn web architecture best practices to help you build single-page, multi-page, and hybrid web apps with Express. Express strikes a balance between a robust framework and no framework at all, allowing you a free hand in your architecture choices. With this book, frontend and backend engineers familiar with JavaScript will discover new ways of looking at web development.",
        "cover": "https://images-na.ssl-images-amazon.com/images/I/71YnSAofw2L._AC_UL600_SR456,600_.jpg",
        "quantity": 0
    },
    {
        "id": "15",
        "title": "React and React Native",
        "author": "Adam Boduch",
        "year": "2017",
        "language": "English",
        "pages": "485",
        "price": 3184,
        "description": "React and React Native allows you to build cross-platform desktop and mobile applications using Facebook's innovative UI libraries. Combined with the Flux data architecture and Relay, you can now create powerful and feature-complete applications from just one code base! This book is split into three parts. The first part shows you how to start crafting composable UIs using React, from rendering with JSX and creating reusable components through to routing and creating isomorphic applications that run on Node. We then move on to showing you how to take the concepts of React and apply them to building Native UIs using React Native. You'll find out how to build responsive and streamlined UIs that can properly handle user interactions in a mobile environment. You'll also learn how to access device-specific APIs such as the geolocation API, and how to handle offline development with React Native. Finally, we'll tie all of these skills together and shows you how you can create React applications that run on every major platform. As well as understanding application state in depth, you'll learn how to leverage Relay to make feature-complete, data-driven web and native mobile applications.",
        "cover": "https://images-na.ssl-images-amazon.com/images/I/71qchBpytTL.jpg",
        "quantity": 0
    },
    {
        "id": "16",
        "title": "Object-Oriented JavaScript",
        "author": "Kumar Chetan Sharma and Stoyan Stefanov",
        "year": "2013",
        "language": "English",
        "pages": "578",
        "price": 2147,
        "description": "You will first be introduced to object-oriented programming, then to the basics of objects in JavaScript. This book takes a do-it-yourself approach when it comes to writing code, because the best way to really learn a programming language is by writing code. You are encouraged to type code into Firebug's console, see how it works and then tweak it and play around with it. There are practice questions at the end of each chapter to help you review what you have learned.For new to intermediate JavaScript developer who wants to prepare themselves for web development problems solved by smart JavaScript!",
        "cover": "https://images-na.ssl-images-amazon.com/images/I/71wLOuQHF5L.jpg",
        "quantity": 0
    },
    {
        "id": "17",
        "title": "100 Things Every Designer Needs to Know About People",
        "author": "Adam BoduchSusan Weinschenk",
        "year": "2011",
        "language": "English",
        "pages": "339",
        "price": 1800,
        "description": "We design to elicit responses from people. We want them to buy something, read more, or take action of some kind. Designing without understanding what makes people act the way they do is like exploring a new city without a map: results will be haphazard, confusing, and inefficient. This book combines real science and research with practical examples to deliver a guide every designer needs. With it you’ll be able to design more intuitive and engaging work for print, websites, applications, and products that matches the way people think, work, and play.",
        "cover": "https://dailydesignnews.com/wp-content/uploads/2018/04/100-things-every-designer-needs-to-know-about-people.jpg",
        "quantity": 0
    },
    {
        "id": "18",
        "title": "Electron Projects: Build Over 9 Cross-platform Desktop Applications from Scratch",
        "author": "Denis Vulka",
        "year": "2019",
        "language": "English",
        "pages": "429",
        "price": 2183,
        "description": "The Electron framework allows you to use modern web technologies to build applications that share the same code across all operating systems and platforms. This also helps designers to easily transition from the web to the desktop. Electron Projects guides you through building cross-platform Electron apps with modern web technologies and JavaScript frameworks such as Angular, React.js, and Vue.js. You’ll explore the process of configuring modern JavaScript frameworks and UI libraries, real-time analytics and automatic updates, and interactions with the operating system. You’ll get hands-on with building a basic Electron app, before moving on to implement a Markdown Editor. In addition to this, you’ll be able to experiment with major JavaScript frameworks such as Angular and Vue.js, discovering ways to integrate them with Electron apps for building cross-platform desktop apps. Later, you’ll learn to build a screenshot snipping tool, a mini-game, and a music player, while also gaining insights into analytics, bug tracking, and licensing. You’ll then get to grips with building a chat app, an eBook generator and finally a simple digital wallet app. By the end of this book, you’ll have experience in building a variety of projects and project templates that will help you to apply your knowledge when creating your own cross-platform applications.",
        "cover": "https://pbs.twimg.com/media/EMAv6nPX0AEjigL.jpg",
        "quantity": 0
    },
    {
        "id": "19",
        "title": "Introducing HTML5",
        "author": "Bruce Lawson and Remy Sharp",
        "year": "1900",
        "language": "English",
        "pages": "312",
        "price": 540,
        "description": "HTML5 continues to evolve, browsers are implementating at break-neck speed and HTML5 web sites spring up like flowers after rain. More than ever, you need to get acquainted with the powerful new possibilities in web and application design. That’s why we’ve crafted a second edition of this book to help you stay on top of current developments. This book shows you how to start adapting the language now to realize its benefits on today’s browsers. It concentrates on the practical―the problems HTML5 can solve for you right away.",
        "cover": "https://s3-ap-southeast-1.amazonaws.com/media.evaly.com.bd/watermarked/2018-06-05_084316.625416introducing-html5-2e.jpg",
        "quantity": 0
    },
    {
        "id": "20",
        "title": "Professional JavaScript for Web Developers",
        "author": "Nicholas C. Zakas",
        "year": "2005",
        "language": "English",
        "pages": "1200",
        "price": 3173,
        "description": "Professional JavaScript for Web Developers is the essential guide to next-level JavaScript development. Written for intermediate-to-advanced programmers, this book jumps right into the technical details to help you clean up your code and become a more sophisticated JavaScript developer. From JavaScript-specific object-oriented programming and inheritance, to combining JavaScript with HTML and other markup languages, expert instruction walks you through the fundamentals and beyond. This new fourth edition has been updated to cover ECMAScript 6 and 7 (also known as ES2015 and ES2016) and the major re-imagination and departure from ES 5.1; new frameworks and libraries, new techniques, new testing tools, and more are explained in detail for the professional developer, with a practical focus that helps you put your new skills to work on real-world projects.",
        "cover": "https://image.isu.pub/200121120000-9d020e805034526db82e35cd4f1596f9/jpg/page_1.jpg",
        "quantity": 0
    }
];

export default BOOKS;